# Generated by Django 5.0.3 on 2024-04-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_guardian_details_name_alter_students_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='Role',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
