# Generated by Django 5.0.3 on 2024-04-20 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_students_role'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='students',
            new_name='Employee',
        ),
        migrations.DeleteModel(
            name='Guardian_details',
        ),
    ]
