# Generated by Django 5.0.3 on 2024-04-21 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='image',
        ),
    ]
