# Generated by Django 5.0.3 on 2024-04-23 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_employee_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.IntegerField(default=0)),
                ('DOB', models.DateField()),
                ('hire_date', models.DateField()),
                ('salary', models.IntegerField(default=0)),
                ('Description', models.TextField(max_length=500, null=True)),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.department')),
                ('Role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.role')),
            ],
        ),
    ]
