# Generated by Django 5.0.3 on 2024-04-23 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_data_employee_delete_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='image',
        ),
        migrations.AddField(
            model_name='employee',
            name='DOB',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='employee',
            name='Department',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.department'),
        ),
        migrations.AddField(
            model_name='employee',
            name='Description',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='Phone',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='Role',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.role'),
        ),
        migrations.AddField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Employee_details',
        ),
        migrations.AddField(
            model_name='employee',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
