# Generated by Django 5.0.3 on 2024-04-23 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_delete_data_remove_employee_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='name',
            new_name='Name',
        ),
    ]
