# Generated by Django 5.0.3 on 2024-04-23 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_rename_name_department_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Department',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='dep_name', to='home.department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Role',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='role', to='home.role'),
        ),
    ]
