# Generated by Django 5.0.3 on 2024-04-23 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='image',
        ),
    ]
