# Generated by Django 5.0.3 on 2024-04-25 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Address',
            new_name='address_of_contact',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='email',
            new_name='email_of_contact',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='message',
            new_name='message_of_contact',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='name_contact',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='phone',
            new_name='phone_of_contact',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='subject',
            new_name='subject_of_contact',
        ),
    ]
