# Generated by Django 5.0.3 on 2024-04-28 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_rename_contact_contact_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='Address',
        ),
    ]
