# Generated by Django 5.0.3 on 2024-05-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_department_role_employee_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
