# Generated by Django 5.0.3 on 2024-05-04 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_department_employee_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='name',
            new_name='Name',
        ),
    ]
