# Generated by Django 5.0.3 on 2024-05-04 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_alter_employee_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='department',
        ),
        migrations.DeleteModel(
            name='role',
        ),
    ]
