# Generated by Django 5.0.3 on 2024-05-04 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_department_role_employee_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.DeleteModel(
            name='department',
        ),
    ]
